### ISSUE TITLE
Doesn't compile on io.js

### ISSUE THREAD

**Issue by tipiirai** [hoedown/node-hoedown#2]
The first error is

``` sh
In file included from ../src/common.hpp:4:
../src/v8u/v8u.hpp:101:5: error: 'New' is a private member of 'v8::PersistentBase<v8::Value>'
```

Thank you for hoedown!

**Comment by jmendeth** [comment]
Yep, V8U currently doesn't support the new API. I *think* this will be fixed when I switch to NAN, which I'll do soon.

**Comment by tipiirai** [comment]
Awesome. Thank you for the update.

**Comment by mildsunrise** [comment]
Finished migration to NAN, the module should work on io.js but I'm not quite sure.

**Comment by tipiirai** [comment]
Unfortunately I cannot go with Hoedown after all since custom renderers are crucial. Thank you anyway.

**Comment by mildsunrise** [comment]
No worries! Closing this for now anyway.

**Comment by mildsunrise** [comment]
BTW, I'm curious, what are you currently using custom renderers for?

**Comment by tipiirai** [comment]
As an example I want `![Hey!](/image.png "inset")` to be rendered as 

``` html
<figure class="inset">
  <img src="image.png">
  <figcaption>Hey</figcaption>
</figure>
```

I have many other custom renderers as well. I want to provide some extra powers for Markdown authors so they don't need to resort to HTML so often.

**Comment by mildsunrise** [comment]
I like it, but what if someone just wants an inline image such as a badge?

**Comment by tipiirai** [comment]
By leaving out the class name: `![Hey!](/image.png)`. This custom markdown is part of an opinionated CMS system and my goal is not to be 100% standards compliant.

**Comment by mildsunrise** [comment]
Hmm, interesting...
